[2024-11-21T01:09:45.795+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T01:09:45.806+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing_dag.normalize_data manual__2024-11-21T01:09:35.386387+00:00 [queued]>
[2024-11-21T01:09:45.812+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing_dag.normalize_data manual__2024-11-21T01:09:35.386387+00:00 [queued]>
[2024-11-21T01:09:45.813+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T01:09:45.823+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): normalize_data> on 2024-11-21 01:09:35.386387+00:00
[2024-11-21T01:09:45.833+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'data_processing_dag', 'normalize_data', 'manual__2024-11-21T01:09:35.386387+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/dag2.py', '--cfg-path', '/tmp/tmpf1xeg3n4']
[2024-11-21T01:09:45.834+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9842) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-21T01:09:45.836+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask normalize_data
[2024-11-21T01:09:45.836+0000] {standard_task_runner.py:72} INFO - Started process 9855 to run task
[2024-11-21T01:09:45.868+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing_dag.normalize_data manual__2024-11-21T01:09:35.386387+00:00 [running]> on host 2276f79c0942
[2024-11-21T01:09:45.916+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_processing_dag' AIRFLOW_CTX_TASK_ID='normalize_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T01:09:35.386387+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T01:09:35.386387+00:00'
[2024-11-21T01:09:45.917+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T01:09:45.987+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-21T01:09:45.994+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T01:09:45.994+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_processing_dag, task_id=normalize_data, run_id=manual__2024-11-21T01:09:35.386387+00:00, execution_date=20241121T010935, start_date=20241121T010945, end_date=20241121T010945
[2024-11-21T01:09:46.011+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-21T01:09:46.023+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-21T01:09:46.024+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
